class Api::V1::Accounts::Whatsapp::CallsController < Api::V1::Accounts::BaseController
  # Authorize using Conversation policy only for actions that set @conversation via before_action
  before_action -> { check_authorization(Conversation) }, only: [:create, :history, :terminate]
  before_action :set_conversation, only: [:create, :history, :terminate]
  before_action :set_inbox, only: [:create, :terminate, :request_permission, :check_permission]
  before_action :validate_calling_enabled, only: [:create, :request_permission]

  # POST /api/v1/accounts/:account_id/whatsapp/calls
  # Initiate an outbound call to a contact
  def create
    result = Whatsapp::Calling::OutboundCallService.initiate_call(
      account: Current.account,
      inbox: @inbox,
      contact: @conversation.contact,
      user: Current.user,
      conversation: @conversation
    )

    render json: {
      message: 'Call initiated successfully',
      call_id: result[:call_id],
      conversation_id: @conversation.display_id,
      status: result[:status]
    }, status: :ok
  rescue Whatsapp::Calling::OutboundCallService::PermissionError => e
    render json: {
      error: e.message,
      error_code: 'PERMISSION_DENIED'
    }, status: :forbidden
  rescue Whatsapp::Calling::OutboundCallService::LimitError => e
    render json: {
      error: e.message,
      error_code: 'LIMIT_EXCEEDED'
    }, status: :too_many_requests
  rescue Whatsapp::Calling::OutboundCallService::CallInitiationError => e
    render json: {
      error: e.message,
      error_code: 'INITIATION_FAILED'
    }, status: :unprocessable_entity
  rescue Whatsapp::Calling::ApiAdapter::NetworkError
    render json: {
      error: 'WhatsApp service temporarily unavailable',
      error_code: 'WHATSAPP_API_UNAVAILABLE',
      retry_after: 30
    }, status: :service_unavailable
  rescue Whatsapp::Calling::ApiAdapter::RateLimitError => e
    render json: {
      error: e.message,
      error_code: 'RATE_LIMIT_EXCEEDED',
      retry_after: e.retry_after
    }, status: :too_many_requests
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/:call_id/accept
  # Accept an incoming call
  def accept
    call_id = params[:call_id]

    if call_id.blank?
      return render json: {
        error: 'Call ID is required',
        error_code: 'MISSING_CALL_ID'
      }, status: :bad_request
    end

    # Find the WhatsappCall record
    whatsapp_call = WhatsappCall.find_by(call_id: call_id, account: Current.account)

    unless whatsapp_call
      return render json: {
        error: 'Call not found',
        error_code: 'CALL_NOT_FOUND'
      }, status: :not_found
    end

    # Verify it's an inbound call
    unless whatsapp_call.direction == 'inbound'
      return render json: {
        error: 'Can only accept inbound calls',
        error_code: 'INVALID_DIRECTION'
      }, status: :unprocessable_entity
    end

    # Accept the call - send accept to WhatsApp API
    conversation = whatsapp_call.conversation
    inbox = conversation.inbox
    channel = inbox.channel

    # Get SDP answer from frontend (generated by WebRTC)
    sdp_answer = params[:sdp_answer]

    if sdp_answer.blank?
      return render json: {
        error: 'SDP answer is required',
        error_code: 'MISSING_SDP_ANSWER'
      }, status: :unprocessable_entity
    end

    Rails.logger.info "[WHATSAPP_CALLS] Accepting call with SDP answer from frontend (length: #{sdp_answer.length})"

    # Call WhatsApp API to accept the call
    api_adapter = Whatsapp::Calling::ApiAdapter.new(channel)
    accept_result = api_adapter.accept_call(call_id: call_id, sdp_answer: sdp_answer)

    if accept_result[:success]
      # Update WhatsappCall status
      whatsapp_call.update!(
        status: 'connected',
        connected_at: Time.current,
        accepted_by_user: Current.user
      )

      # Update conversation
      conversation.update!(
        additional_attributes: conversation.additional_attributes.merge(
          'call_status' => 'connected',
          'accepted_at' => Time.current.to_i,
          'accepted_by' => Current.user.id
        )
      )

      # Broadcast event
      ActionCable.server.broadcast(
        "account_#{Current.account.id}",
        {
          event: 'whatsapp_call_accepted',
          data: {
            account_id: Current.account.id,
            call_id: call_id,
            conversation_id: conversation.display_id,
            accepted_by: Current.user.name
          }
        }
      )

      Rails.logger.info "[WHATSAPP_CALLS] Call #{call_id} accepted successfully by #{Current.user.name}"

      render json: {
        message: 'Call accepted successfully',
        call_id: call_id,
        conversation_id: conversation.display_id,
        sdp_answer: accept_result[:sdp_answer]
      }, status: :ok
    else
      Rails.logger.error "[WHATSAPP_CALLS] WhatsApp API accept failed: #{accept_result[:error]}"
      render json: {
        error: 'Failed to accept call with WhatsApp',
        error_code: 'WHATSAPP_ACCEPT_FAILED',
        details: accept_result[:error]
      }, status: :unprocessable_entity
    end
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Accept failed: #{e.class} - #{e.message}"
    render json: {
      error: 'Failed to accept call',
      error_code: 'ACCEPT_ERROR'
    }, status: :unprocessable_entity
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/answer
  # Answer an incoming call (call_id in body, not URL)
  def answer
    call_id = params[:call_id]

    if call_id.blank?
      return render json: {
        error: 'Call ID is required',
        error_code: 'MISSING_CALL_ID'
      }, status: :bad_request
    end

    # Find the WhatsappCall record
    whatsapp_call = WhatsappCall.find_by(call_id: call_id, account: Current.account)

    unless whatsapp_call
      return render json: {
        error: 'Call not found',
        error_code: 'CALL_NOT_FOUND'
      }, status: :not_found
    end

    # Verify it's an inbound call
    unless whatsapp_call.direction == 'inbound'
      return render json: {
        error: 'Can only answer inbound calls',
        error_code: 'INVALID_DIRECTION'
      }, status: :unprocessable_entity
    end

    # Answer the call - send answer to WhatsApp API
    conversation = whatsapp_call.conversation
    inbox = conversation.inbox
    channel = inbox.channel

    # Auto-assign conversation to accepting agent if unassigned
    if conversation.assignee.blank?
      Conversations::AssignmentService.new(
        conversation: conversation,
        assignee_id: Current.user.id
      ).perform
      Rails.logger.info "[WHATSAPP_CALLS] Auto-assigned conversation #{conversation.display_id} to user #{Current.user.id}"
    end

    # Get SDP answer from frontend (generated by WebRTC)
    sdp_answer = params[:sdp_answer]

    if sdp_answer.blank?
      return render json: {
        error: 'SDP answer is required',
        error_code: 'MISSING_SDP_ANSWER'
      }, status: :unprocessable_entity
    end

    Rails.logger.info "[WHATSAPP_CALLS] Answering call #{call_id} with SDP answer from frontend (length: #{sdp_answer.length})"

    begin
      # Call WhatsApp API to accept the call
      api_adapter = Whatsapp::Calling::ApiAdapter.new(channel)
      api_response = api_adapter.accept_call(call_id: call_id, sdp_answer: sdp_answer)

      Rails.logger.info "[WHATSAPP_CALLS] WhatsApp API accept successful: #{api_response.inspect}"

      # Update WhatsappCall status
      whatsapp_call.update!(
        status: 'connected',
        connected_at: Time.current,
        accepted_by_user: Current.user
      )

      # Update conversation
      conversation.update!(
        additional_attributes: conversation.additional_attributes.merge(
          'call_status' => 'connected',
          'accepted_at' => Time.current.to_i,
          'accepted_by' => Current.user.id
        )
      )

      # Broadcast event
      ActionCable.server.broadcast(
        "account_#{Current.account.id}",
        {
          event: 'whatsapp_call_accepted',
          data: {
            account_id: Current.account.id,
            call_id: call_id,
            conversation_id: conversation.display_id,
            accepted_by: Current.user.name
          }
        }
      )

      render json: {
        success: true,
        call_id: call_id,
        status: 'connected'
      }
    rescue Whatsapp::Calling::ApiAdapter::ApiError => e
      Rails.logger.error "[WHATSAPP_CALLS] WhatsApp API accept failed: #{e.message}"
      render json: {
        error: 'Failed to answer call with WhatsApp',
        error_code: 'WHATSAPP_ANSWER_FAILED',
        details: e.message
      }, status: :unprocessable_entity
    rescue StandardError => e
      Rails.logger.error "[WHATSAPP_CALLS] Answer failed: #{e.class} - #{e.message}"
      Rails.logger.error e.backtrace.join("\n")
      render json: {
        error: 'Failed to answer call',
        error_code: 'ANSWER_ERROR',
        details: e.message
      }, status: :unprocessable_entity
    end
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/:call_id/reject
  # Reject an incoming call
  def reject
    call_id = params[:call_id]
    reason = params[:reason] || 'declined'

    if call_id.blank?
      return render json: {
        error: 'Call ID is required',
        error_code: 'MISSING_CALL_ID'
      }, status: :bad_request
    end

    # Find the WhatsappCall record
    whatsapp_call = WhatsappCall.find_by(call_id: call_id, account: Current.account)

    unless whatsapp_call
      return render json: {
        error: 'Call not found',
        error_code: 'CALL_NOT_FOUND'
      }, status: :not_found
    end

    # Verify it's an inbound call
    unless whatsapp_call.direction == 'inbound'
      return render json: {
        error: 'Can only reject inbound calls',
        error_code: 'INVALID_DIRECTION'
      }, status: :unprocessable_entity
    end

    # Reject the call
    conversation = whatsapp_call.conversation
    inbox = conversation.inbox

    # Call WhatsApp API to reject
    api_adapter = Whatsapp::Calling::ApiAdapter.new(inbox.channel)
    api_adapter.reject_call(call_id: call_id)

    # Update status regardless of API result (best effort)
    # Update WhatsappCall status
    whatsapp_call.update!(
      status: 'rejected',
      ended_at: Time.current,
      rejection_reason: reason
    )

    # Update conversation
    conversation.update!(
      additional_attributes: conversation.additional_attributes.merge(
        'call_status' => 'rejected',
        'rejected_at' => Time.current.to_i,
        'rejected_by' => Current.user.id,
        'rejection_reason' => reason
      )
    )

    # Create rejected message
    builder = Whatsapp::Calling::CallMessageBuilder.new(
      conversation: conversation,
      whatsapp_call: whatsapp_call
    )
    builder.create_failed_message(reason: 'rejected')

    # Broadcast event
    ActionCable.server.broadcast(
      "account_#{Current.account.id}",
      {
        event: 'whatsapp_call_rejected',
        call_id: call_id,
        conversation_id: conversation.display_id,
        rejected_by: Current.user.name,
        reason: reason
      }
    )

    render json: {
      message: 'Call rejected successfully',
      call_id: call_id
    }, status: :ok
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Reject failed: #{e.class} - #{e.message}"
    render json: {
      error: 'Failed to reject call',
      error_code: 'REJECT_ERROR'
    }, status: :unprocessable_entity
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/:call_id/terminate
  # Terminate an active call
  def terminate
    call_id = params[:call_id]
    conversation_id = params[:conversation_id]

    Rails.logger.info "[WHATSAPP_CALLS] Terminate request - call_id: #{call_id}, conversation: #{conversation_id}"

    if call_id.blank?
      Rails.logger.warn '[WHATSAPP_CALLS] No call_id provided in terminate request'
      return render json: {
        error: 'Call ID is required',
        error_code: 'MISSING_CALL_ID'
      }, status: :bad_request
    end

    # Find the WhatsappCall record to check if already terminated
    whatsapp_call = WhatsappCall.find_by(call_id: call_id, account: Current.account)

    if whatsapp_call && whatsapp_call.status == 'completed'
      Rails.logger.info "[WHATSAPP_CALLS] Call #{call_id} already terminated, skipping"
      return render json: { message: 'Call already terminated' }, status: :ok
    end

    Rails.logger.info "[WHATSAPP_CALLS] Terminating call #{call_id} on WhatsApp API"

    api_adapter = Whatsapp::Calling::ApiAdapter.new(@inbox.channel)
    api_adapter.terminate_call(call_id: call_id)

    Rails.logger.info "[WHATSAPP_CALLS] Call #{call_id} terminated successfully on WhatsApp"

    render json: { message: 'Call terminated successfully' }, status: :ok
  rescue Whatsapp::Calling::ApiAdapter::NetworkError => e
    Rails.logger.error "[WHATSAPP_CALLS] Network error: #{e.message}"
    render json: {
      error: 'WhatsApp service temporarily unavailable',
      error_code: 'WHATSAPP_API_UNAVAILABLE',
      retry_after: 30
    }, status: :service_unavailable
  rescue Whatsapp::Calling::ApiAdapter::TimeoutError => e
    Rails.logger.error "[WHATSAPP_CALLS] Timeout error: #{e.message}"
    render json: {
      error: 'Request timed out',
      error_code: 'TIMEOUT',
      retry_after: 10
    }, status: :gateway_timeout
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Terminate failed: #{e.class} - #{e.message}"
    render json: {
      error: 'Failed to terminate call',
      error_code: 'TERMINATION_FAILED'
    }, status: :unprocessable_entity
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/permissions
  # Request permission from a contact to make calls
  def request_permission
    contact = Current.account.contacts.find_by(id: params[:contact_id])

    return render json: { error: 'Contact not found' }, status: :not_found unless contact

    permission = Whatsapp::Calling::PermissionRequestService.request_permission(
      account: Current.account,
      inbox: @inbox,
      contact: contact,
      user: Current.user
    )

    render json: {
      message: 'Permission request sent successfully',
      permission: permission_json(permission)
    }, status: :ok
  rescue Whatsapp::Calling::PermissionRequestService::AlreadyRequestedError => e
    render json: { error: e.message }, status: :conflict
  rescue Whatsapp::Calling::PermissionRequestService::PermissionError => e
    render json: { error: e.message }, status: :unprocessable_entity
  end

  # GET /api/v1/accounts/:account_id/whatsapp/calls/permissions
  # Get permission status for a contact
  def check_permission
    contact = Current.account.contacts.find_by(id: params[:contact_id])

    return render json: { error: 'Contact not found' }, status: :not_found unless contact

    permission = Whatsapp::CallPermission.find_by(
      account: Current.account,
      inbox: @inbox,
      contact: contact,
      phone_number_id: @channel.phone_number_id
    )

    if permission
      render json: { permission: permission_json(permission) }, status: :ok
    else
      render json: {
        permission: {
          status: 'not_requested',
          can_request: true,
          remaining_calls: 0
        }
      }, status: :ok
    end
  end

  # GET /api/v1/accounts/:account_id/whatsapp/calls/history
  # Get call history for a conversation
  def history
    page = params[:page] || 1
    per_page = params[:per_page] || 20

    calls = extract_call_history(@conversation)
    paginated_calls = Kaminari.paginate_array(calls).page(page).per(per_page)

    render json: {
      calls: paginated_calls,
      meta: {
        current_page: paginated_calls.current_page,
        total_pages: paginated_calls.total_pages,
        total_count: calls.length,
        has_more: paginated_calls.current_page < paginated_calls.total_pages
      }
    }, status: :ok
  end

  # GET /api/v1/accounts/:account_id/whatsapp/calls/analytics
  # Get call analytics for an inbox or account
  def analytics
    start_date = params[:start_date] ? Time.zone.parse(params[:start_date]) : 30.days.ago
    end_date = params[:end_date] ? Time.zone.parse(params[:end_date]) : Time.zone.now
    inbox_id = params[:inbox_id]

    # Use WhatsappCall model for better performance
    calls = Current.account.whatsapp_calls
                   .for_date_range(start_date, end_date)

    calls = calls.for_inbox(inbox_id) if inbox_id.present?

    analytics_data = calculate_analytics_from_calls(calls)

    render json: { analytics: analytics_data }, status: :ok
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/setup_webrtc
  def setup_webrtc
    Rails.logger.info "[WHATSAPP_CALLS] setup_webrtc - P2P mode with WhatsApp, params: conversation_id=#{params[:conversation_id]}, call_id=#{params[:call_id]}"
    conversation = find_conversation_for_webrtc(params[:conversation_id], params[:call_id])
    return render json: { error: 'Conversation not found' }, status: :not_found unless conversation

    authorize conversation, :show?

    call_id_param = params[:call_id]
    sdp_offer = params[:sdp_offer]

    if sdp_offer.present?
      Rails.logger.info '[WHATSAPP_CALLS] setup_webrtc - Initiating P2P call with WhatsApp'

      setup_result = conversation.with_lock do
        persist_browser_sdp_offer(conversation, sdp_offer, call_id_param)

        Whatsapp::Calling::WebrtcSetupService.new(
          account: Current.account,
          inbox: conversation.inbox,
          conversation: conversation,
          call_id: call_id_param,
          sdp_offer: sdp_offer
        ).perform
      end

      Rails.logger.info "[WHATSAPP_CALLS] setup_webrtc - Result: success=#{setup_result[:success]}"

      unless setup_result[:success]
        # Update initiated message to show error when WhatsApp API fails
        handle_webrtc_setup_error(conversation, call_id_param, setup_result[:error])
        return render json: { error: setup_result[:error] }, status: :unprocessable_entity
      end

      call_id = setup_result[:call_id]
    end

    # Get WhatsApp SDP answer
    whatsapp_call = conversation.additional_attributes&.dig('whatsapp_call') || {}
    sdp_answer = whatsapp_call['whatsapp_sdp_answer'] || whatsapp_call['sdp_answer']
    call_id ||= whatsapp_call['id'] || call_id_param

    if sdp_answer.present?
      Rails.logger.info '[WHATSAPP_CALLS] setup_webrtc - Returning WhatsApp SDP answer'
      render json: { callId: call_id, sdpAnswer: sdp_answer }, status: :ok
    else
      Rails.logger.info '[WHATSAPP_CALLS] setup_webrtc - SDP answer pending'
      render json: { callId: call_id, message: 'SDP answer pending' }, status: :accepted
    end
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] setup_webrtc failed: #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
    render json: { error: e.message }, status: :unprocessable_entity
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/trickle
  # ICE candidate endpoint - not needed in P2P mode but keeping for compatibility
  def trickle
    Rails.logger.info '[WHATSAPP_CALLS] trickle called (P2P mode - no action needed)'
    render json: { message: 'P2P mode - ICE candidates handled by browser' }, status: :ok
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/:id/recording
  # Upload call recording from browser (call_id in path)
  def recording
    call_id = CGI.unescape(params[:id])  # Decode URL-encoded call_id
    process_recording_upload(call_id, params[:recording], params[:duration])
  end

  # POST /api/v1/accounts/:account_id/whatsapp/calls/recording_upload
  # Upload call recording with call_id in the request body (FormData)
  def recording_upload
    call_id = CGI.unescape(params[:call_id].to_s)
    process_recording_upload(call_id, params[:recording], params[:duration])
  end

  private

  def set_conversation
    @conversation = Current.account.conversations.find_by(id: params[:conversation_id])
    return render json: { error: 'Conversation not found' }, status: :not_found unless @conversation
  end

  def set_inbox
    inbox_id = @conversation&.inbox_id || params[:inbox_id]
    @inbox = Current.account.inboxes.find_by(id: inbox_id)
    return render json: { error: 'Inbox not found' }, status: :not_found unless @inbox

    return if @inbox.channel_type == 'Channel::Whatsapp'

    render json: { error: 'Not a WhatsApp inbox' }, status: :bad_request
  end

  def validate_calling_enabled
    return if @inbox.channel.calling_enabled?

    render json: { error: 'Calling is not enabled for this WhatsApp channel' }, status: :forbidden
  end

  def permission_json(permission)
    {
      id: permission.id,
      status: permission.status,
      granted: permission.granted?,
      can_make_call: permission.can_make_call?,
      remaining_calls: permission.remaining_calls,
      expires_at: permission.expires_at,
      granted_at: permission.granted_at,
      requested_at: permission.requested_at
    }
  end

  def extract_call_history(conversation)
    # Extract calls from messages with content_type 'call'
    # Preload contact to avoid N+1
    call_messages = conversation.messages
                                .includes(:sender)
                                .where(content_type: 'call')
                                .order(created_at: :desc)

    # Cache contact info to avoid repeated lookups
    contact_name = conversation.contact.name
    contact_number = conversation.contact.phone_number

    call_messages.map do |message|
      attrs = message.content_attributes || {}
      {
        id: attrs['call_id'],
        direction: attrs['direction'],
        status: attrs['status'],
        duration: attrs['duration'],
        initiated_at: attrs['initiated_at'],
        answered_at: attrs['answered_at'],
        ended_at: attrs['ended_at'],
        end_reason: attrs['end_reason'],
        recording_url: attrs['recording_url'],
        quality_metrics: attrs['quality_metrics'],
        contact_name: contact_name,
        contact_number: contact_number,
        created_at: message.created_at
      }
    end
  end

  def calculate_analytics_from_calls(calls)
    # Use ActiveRecord aggregations for better performance
    total_calls = calls.count
    inbound_calls = calls.direction_inbound.count
    outbound_calls = calls.direction_outbound.count
    completed_calls = calls.successful.count
    failed_calls = calls.where(status: %w[failed rejected timeout cancelled]).count
    total_duration = calls.successful.sum(:duration_seconds)

    {
      total_calls: total_calls,
      inbound_calls: inbound_calls,
      outbound_calls: outbound_calls,
      completed_calls: completed_calls,
      failed_calls: failed_calls,
      success_rate: total_calls.positive? ? ((completed_calls.to_f / total_calls) * 100).round(2) : 0,
      average_duration: completed_calls.positive? ? (total_duration.to_f / completed_calls).round(2) : 0,
      total_duration: total_duration
    }
  end

  def check_or_create_permission(contact)
    Whatsapp::CallPermission.find_or_create_by!(
      account: Current.account,
      inbox: @inbox,
      contact: contact,
      phone_number_id: @channel.phone_number_id
    ) do |permission|
      permission.permission_status = 'pending'
    end
  end

  def find_conversation_for_webrtc(conversation_id, call_id)
    if conversation_id.present?
      conversation = Current.account.conversations.find_by(id: conversation_id)
      return conversation if conversation
    end

    return nil if call_id.blank?

    Current.account.conversations.find_by(identifier: call_id) ||
      Current.account.conversations.where("additional_attributes -> 'whatsapp_call' ->> 'id' = ?", call_id).first
  end

  def persist_browser_sdp_offer(conversation, sdp_offer, call_id)
    return unless conversation

    attrs = (conversation.additional_attributes || {}).deep_dup
    whatsapp_call = attrs['whatsapp_call'] || {}
    updated = false

    if sdp_offer.present?
      whatsapp_call['browser_sdp_offer'] = sdp_offer
      updated = true
    end

    if call_id.present?
      whatsapp_call['id'] = call_id
      updated = true
    end

    return unless updated

    attrs['whatsapp_call'] = whatsapp_call
    conversation.update!(additional_attributes: attrs)
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Failed to persist browser offer: #{e.message}"
  end

  def save_recording_file(whatsapp_call, recording_file)
    # Create recordings directory if it doesn't exist
    recordings_dir = Rails.root.join('storage/call_recordings')
    FileUtils.mkdir_p(recordings_dir)

    # Generate unique filename
    timestamp = Time.current.strftime('%Y%m%d_%H%M%S')
    filename = "call_#{whatsapp_call.call_id}_#{timestamp}.webm"
    file_path = recordings_dir.join(filename)

    # Save file
    File.binwrite(file_path, recording_file.read)

    Rails.logger.info "[WHATSAPP_CALLS] Recording saved to: #{file_path}"

    # Return relative path for storage
    "call_recordings/#{filename}"
  end

  def create_recording_message(whatsapp_call, recording_path)
    conversation = whatsapp_call.conversation
    return unless conversation

    # Create message with recording attachment
    message = conversation.messages.create!(
      account: whatsapp_call.account,
      inbox: whatsapp_call.inbox,
      message_type: :activity,
      content: "Grabación de llamada (#{format_duration(whatsapp_call.duration)})",
      sender: nil
    )

    # Attach recording file
    full_path = Rails.root.join('storage', recording_path)
    if File.exist?(full_path)
      message.attachments.create!(
        account: whatsapp_call.account,
        file: File.open(full_path),
        file_type: :audio
      )
      Rails.logger.info "[WHATSAPP_CALLS] Recording message created: message_id=#{message.id}"
    else
      Rails.logger.error "[WHATSAPP_CALLS] Recording file not found: #{full_path}"
    end
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Failed to create recording message: #{e.message}"
  end

  def process_recording_upload(call_id, recording_file, duration_param = nil)
    Rails.logger.info "[WHATSAPP_CALLS] Recording upload - call_id=#{call_id}, file present=#{recording_file.present?}, duration=#{duration_param}"

    return render json: { error: 'No recording file provided' }, status: :unprocessable_entity if recording_file.blank?

    whatsapp_call = WhatsappCall.find_by(call_id: call_id, account: Current.account)

    unless whatsapp_call
      Rails.logger.warn "[WHATSAPP_CALLS] WhatsappCall record not found for call_id=#{call_id}"
      return render json: { error: 'Call not found' }, status: :not_found
    end

    recording_path = save_recording_file(whatsapp_call, recording_file)

    # Use duration from params (frontend) or fallback to existing duration_seconds
    final_duration = duration_param.present? ? duration_param.to_i : (whatsapp_call.duration_seconds || 0)

    whatsapp_call.update!(
      recording_url: recording_path,
      duration_seconds: final_duration
    )

    create_recording_message(whatsapp_call, recording_path)

    Rails.logger.info "[WHATSAPP_CALLS] Recording saved successfully: #{recording_path}"

    render json: {
      message: 'Recording uploaded successfully',
      recording_path: recording_path
    }, status: :ok
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Failed to save recording: #{e.message}"
    Rails.logger.error e.backtrace.join("\n")
    render json: { error: 'Failed to save recording' }, status: :internal_server_error
  end

  def format_duration(seconds)
    return '0:00' unless seconds&.positive?

    minutes = seconds / 60
    secs = seconds % 60
    "#{minutes}:#{secs.to_s.rjust(2, '0')}"
  end

  def handle_webrtc_setup_error(conversation, call_id, error_message)
    Rails.logger.info '[WHATSAPP_CALLS] ===== handle_webrtc_setup_error STARTED ====='
    Rails.logger.info "[WHATSAPP_CALLS] Updating initiated message to error status for call_id=#{call_id}"
    Rails.logger.info "[WHATSAPP_CALLS] Conversation ID: #{conversation.id}"
    Rails.logger.info "[WHATSAPP_CALLS] Error message: #{error_message}"

    # Extract error code and message from WhatsApp API error
    error_text = error_message.to_s
    error_code = nil

    # Try to extract error code or classify error type
    if error_text =~ /Error code (\d+):/i
      error_code = ::Regexp.last_match(1)
    elsif /No approved call permission/i.match?(error_text)
      error_code = 'NO_CALL_PERMISSION'
    end

    Rails.logger.info "[WHATSAPP_CALLS] Extracted error_code: #{error_code}"

    # Find the "Call initiated..." message by specific call_id
    Rails.logger.info "[WHATSAPP_CALLS] Searching for message with call_id: #{call_id}"
    initiated_message = conversation.messages
                                    .where(message_type: :activity, content_type: :voice_call)
                                    .where("call_metadata->>'call_id' = ?", call_id)
                                    .where(call_status: :call_initiated)
                                    .first

    Rails.logger.info "[WHATSAPP_CALLS] Message found: #{initiated_message.present?}"

    if initiated_message
      Rails.logger.info "[WHATSAPP_CALLS] Found initiated message (id=#{initiated_message.id}), updating to error status"

      # Determine the appropriate error status
      error_status = Message::WhatsappCallMessage.meta_error_to_call_status(error_code, error_text)

      Rails.logger.info "[WHATSAPP_CALLS] Determined error_status: #{error_status}"

      # Get the status message
      status_message = case error_status
                       when :call_error_recipient_not_approved
                         '⚠️ Error: Recipient has not approved receiving calls'
                       when :call_error_unauthorized
                         '⚠️ Error: Not authorized for calling'
                       when :call_error_no_balance
                         '⚠️ Error: Insufficient balance'
                       when :call_error_not_enabled
                         '⚠️ Error: Calling not enabled'
                       when :call_error_rate_limit
                         '⚠️ Error: Rate limit exceeded'
                       when :call_error_invalid
                         '⚠️ Error: Invalid parameters'
                       else
                         '⚠️ Call failed'
                       end

      Rails.logger.info "[WHATSAPP_CALLS] Status message: #{status_message}"

      # Update the existing message to error status
      Rails.logger.info "[WHATSAPP_CALLS] Before update - call_status: #{initiated_message.call_status}, content: #{initiated_message.content}"

      initiated_message.call_status = error_status
      initiated_message.content = status_message
      initiated_message.call_metadata = (initiated_message.call_metadata || {}).merge(
        ended_at: Time.current.to_i,
        error_code: error_code || 'UNKNOWN',
        error_message: error_text
      )

      Rails.logger.info "[WHATSAPP_CALLS] After assignment - call_status: #{initiated_message.call_status}, content: #{initiated_message.content}"

      # Save and get changes before they're cleared
      initiated_message.save!
      changes = initiated_message.previous_changes

      Rails.logger.info '[WHATSAPP_CALLS] Message saved successfully'
      Rails.logger.info "[WHATSAPP_CALLS] Previous changes: #{changes.inspect}"
      Rails.logger.info "[WHATSAPP_CALLS] Message updated to #{error_status} status"

      # Manually dispatch the update event with the changes
      Rails.logger.info '[WHATSAPP_CALLS] Dispatching message.updated event...'
      Rails.configuration.dispatcher.dispatch(
        'message.updated',
        Time.zone.now,
        message: initiated_message,
        performed_by: nil,
        previous_changes: changes
      )
      Rails.logger.info '[WHATSAPP_CALLS] Event dispatched successfully'
      Rails.logger.info '[WHATSAPP_CALLS] ===== handle_webrtc_setup_error COMPLETED ====='
    else
      Rails.logger.warn "[WHATSAPP_CALLS] No initiated message found for call_id=#{call_id}"

      # Fallback: create new error message if initiated message not found
      whatsapp_call = WhatsappCall.new(
        account: Current.account,
        conversation: conversation,
        contact: conversation.contact,
        inbox: conversation.inbox,
        initiated_by_user: current_user,
        call_id: call_id || "error-#{SecureRandom.hex(8)}",
        direction: 'outbound',
        initiated_at: Time.current,
        status: 'failed'
      )

      Whatsapp::Calling::CallMessageBuilder.new(
        conversation: conversation,
        whatsapp_call: whatsapp_call
      ).create_meta_error_message(
        error_code: error_code || 'UNKNOWN',
        error_message: error_text,
        meta_response: nil
      )
    end

    Rails.logger.info '[WHATSAPP_CALLS] Error handling completed'
  rescue StandardError => e
    Rails.logger.error "[WHATSAPP_CALLS] Failed to handle setup error: #{e.message}"
    Rails.logger.error e.backtrace.first(5).join("\n")
  end
end
